# Generated by Django 3.1.7 on 2021-03-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
